# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'categoryShop.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_categoryShopWindow(object):
    def setupUi(self, categoryShopWindow):
        categoryShopWindow.setObjectName("categoryShopWindow")
        categoryShopWindow.resize(1016, 720)
        categoryShopWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(categoryShopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 210, 159, 328))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_11.addWidget(self.pushButton_11)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.pushButton_18 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_18.addWidget(self.pushButton_18)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_15.addWidget(self.pushButton_15)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_12.addWidget(self.pushButton_12)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_14.addWidget(self.pushButton_14)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(480, 610, 93, 28))
        self.backButton.setObjectName("backButton")
        self.productsLabel = QtWidgets.QLabel(self.centralwidget)
        self.productsLabel.setGeometry(QtCore.QRect(90, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.productsLabel.setFont(font)
        self.productsLabel.setObjectName("productsLabel")
        self.cartLabel = QtWidgets.QLabel(self.centralwidget)
        self.cartLabel.setGeometry(QtCore.QRect(580, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cartLabel.setFont(font)
        self.cartLabel.setObjectName("cartLabel")
        categoryShopWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(categoryShopWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 26))
        self.menubar.setObjectName("menubar")
        categoryShopWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(categoryShopWindow)
        self.statusbar.setObjectName("statusbar")
        categoryShopWindow.setStatusBar(self.statusbar)

        self.retranslateUi(categoryShopWindow)
        QtCore.QMetaObject.connectSlotsByName(categoryShopWindow)

    def retranslateUi(self, categoryShopWindow):
        _translate = QtCore.QCoreApplication.translate
        categoryShopWindow.setWindowTitle(_translate("categoryShopWindow", "categoryShop"))
        self.label_3.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("categoryShopWindow", "Buy"))
        self.label_4.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_5.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_5.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_2.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_11.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_11.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_18.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_18.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_15.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_15.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_12.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_12.setText(_translate("categoryShopWindow", "PushButton"))
        self.label_14.setText(_translate("categoryShopWindow", "TextLabel"))
        self.pushButton_14.setText(_translate("categoryShopWindow", "PushButton"))
        self.backButton.setText(_translate("categoryShopWindow", "Back"))
        self.productsLabel.setText(_translate("categoryShopWindow", "Products:"))
        self.cartLabel.setText(_translate("categoryShopWindow", "Cart:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    categoryShopWindow = QtWidgets.QMainWindow()
    ui = Ui_categoryShopWindow()
    ui.setupUi(categoryShopWindow)
    categoryShopWindow.show()
    sys.exit(app.exec_())
